#!/usr/bin/env python3
"""Derives output-styles/proof-first.md and prompts/system-prompt.md
mechanically from skills/proof-first/SKILL.md and four named reference
files.

This script performs no condensation, no rewriting, and no
summarisation: it concatenates source content verbatim under stated
section markers and adds a wrapper around it. It makes no statement
about how a live model session behaves with either derivative; the
committed source for that is evals/routes/RESULTS-routes.md, which
_render_preamble() below names in the output for the same reason, and
which reports a null result rather than equivalence. It imports only
argparse, hashlib, pathlib, re, and sys
from the Python standard library; no package-manager dependency is
introduced by this file or by the CI job that runs it.

Declared ceiling:
  (a) the recorded hash proves a derivative was produced from some
      version of the named sources, not that this script's own
      derivation logic is correct -- a bug here that silently dropped a
      rule would still produce a matching hash;
  (b) the mechanism proves structural freshness only, never anything
      about how a live model session conducts itself;
  (c) a contributor could hand-edit a derivative after generation, and
      the recorded hash alone would not notice -- which is exactly why
      --check compares freshly rendered bytes against committed bytes
      as a second, independent guard.

Usage:
  python3 tools/generate_derivatives.py
      Render both derivatives from the current source files and write
      them to output-styles/proof-first.md and prompts/system-prompt.md,
      overwriting whatever is already there. The writer pins the output
      line ending to LF regardless of the host platform's native line
      ending, so the bytes produced are the same whether this is run on
      the CI runner or on a contributor's own machine.

  python3 tools/generate_derivatives.py --check
      Render both derivatives in memory and compare them byte for byte
      against the committed files. Exit non-zero, naming every file that
      differs, if either committed file does not match freshly rendered
      output.

  Re-sync step this script exists to make mandatory: after any edit to
  skills/proof-first/SKILL.md or to any of the four named reference
  files, run this script with no flag before committing. CI runs
  `python3 tools/generate_derivatives.py --check` and
  tools/check_repo.py's skill-derivative-stale code, either of which
  fails the build if that step was skipped.
"""
import argparse
import hashlib
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

SKILL_PATH = 'skills/proof-first/SKILL.md'

# The three instruction-carrying reference files, in a fixed, stated
# order, followed by checklist.md -- the ID index check mode requires
# reading before emitting any rule citation.
REFERENCE_SOURCES = (
    'skills/proof-first/references/deletion-test.md',
    'skills/proof-first/references/completeness-audit.md',
    'skills/proof-first/references/artifact-patterns.md',
    'skills/proof-first/references/checklist.md',
)

# The full ordered tuple of repository-relative source paths, skill
# first. tools/check_repo.py holds the authoritative copy of this same
# tuple (its own DERIVATIVE_SOURCE_NAMES); the two must agree, and
# check_repo.py's skill-derivative-stale code is what enforces that
# agreement. Neither file imports the other -- a sibling import inside
# tools/ would depend on how the script happens to be invoked, which is
# exactly the fragility this project avoids elsewhere. Written out as a
# literal tuple, not composed from SKILL_PATH/REFERENCE_SOURCES above, so
# both files' tuples are byte-for-byte comparable by a simple text scan.
DERIVATIVE_SOURCE_NAMES = (
    'skills/proof-first/SKILL.md',
    'skills/proof-first/references/deletion-test.md',
    'skills/proof-first/references/completeness-audit.md',
    'skills/proof-first/references/artifact-patterns.md',
    'skills/proof-first/references/checklist.md',
)

# Deliberately omitted. worked-examples.md supplies illustration rather
# than instruction: every rule it illustrates already carries its own
# constructive **Replace with:** line in one of the sources above -- the
# 20 PF rules it illustrates in SKILL.md, the 8 MC rules in
# completeness-audit.md, because mc-rule-in-skill (check_repo.py) makes
# an MC rule defined in SKILL.md a build failure and NUMBERING.md routes
# every MC row to completeness-audit.md. Both files are concatenated
# into both derivatives, so nothing normative is lost by leaving
# worked-examples.md out of either.
OMITTED_SOURCE = 'skills/proof-first/references/worked-examples.md'

# One physical line. Do not wrap it -- a wrapped anchor is the failure
# 02-04 already recorded for a different literal line.
STAMP_TEMPLATE = '<!-- generated by tools/generate_derivatives.py from {paths} sha256:{digest} -->'

OUTPUT_STYLE_PATH = 'output-styles/proof-first.md'
SYSTEM_PROMPT_PATH = 'prompts/system-prompt.md'

FRONTMATTER_RE = re.compile(r'\A---\n(.*?)\n---\n', re.S)
DESCRIPTION_BLOCK_RE = re.compile(r'^description:\s*\|\n((?:[ \t]+\S.*\n?)+)', re.M)


def read_sources(repo_root):
    """Read every path in DERIVATIVE_SOURCE_NAMES as bytes, in tuple
    order. Exit non-zero naming the missing path, writing nothing, if
    any named source is absent."""
    blobs = []
    for name in DERIVATIVE_SOURCE_NAMES:
        path = repo_root / name
        if not path.exists():
            print(f"generate_derivatives: missing source {name}", file=sys.stderr)
            sys.exit(1)
        blobs.append(path.read_bytes())
    return blobs


def source_hash(blobs):
    """One hashlib.sha256 over the concatenated bytes in tuple order,
    returning the lowercase hex digest. One stated recipe, used
    identically by every caller -- the generator here and
    check_repo.py's _hash_sources there."""
    h = hashlib.sha256()
    for blob in blobs:
        h.update(blob)
    return h.hexdigest()


def _skill_frontmatter_and_body(skill_text):
    m = FRONTMATTER_RE.match(skill_text)
    if not m:
        print(f"generate_derivatives: {SKILL_PATH} has no frontmatter block", file=sys.stderr)
        sys.exit(1)
    return m.group(1), skill_text[m.end():]


def _skill_description_block(frontmatter):
    m = DESCRIPTION_BLOCK_RE.search(frontmatter)
    if not m:
        print(f"generate_derivatives: {SKILL_PATH} frontmatter has no 'description: |' block", file=sys.stderr)
        sys.exit(1)
    return m.group(1)


def build_body(blobs):
    """The shared body both derivatives carry, per P4-06: the skill's
    post-frontmatter text first (the leading '---' delimited block
    stripped, everything after it kept verbatim), then each reference
    file's full text verbatim, each introduced by a section marker
    naming its repository-relative source path. Rewrites no sentence
    and reorders nothing inside a source."""
    skill_text = blobs[0].decode('utf-8')
    _, skill_body = _skill_frontmatter_and_body(skill_text)
    parts = [skill_body.strip('\n')]
    for name, blob in zip(REFERENCE_SOURCES, blobs[1:]):
        text = blob.decode('utf-8').strip('\n')
        parts.append(f"---\n\n## Reference source: {name}\n\n{text}")
    return '\n\n'.join(parts) + '\n'


def _render_preamble():
    """The generated preamble, identical in both derivatives and emitted
    by this script rather than typed into either file. States that the
    file is generated and must not be edited by hand; names every source
    path it was built from; names the one deliberately omitted source
    and why; states that installing the skill folder is the fuller
    route; states plainly that this project publishes measured claims or
    none; and points at the committed route comparison rather than
    denying that one exists. That denial is what this function used to
    emit, and it stopped being true when 04-15 committed
    evals/routes/RESULTS-routes.md. The sentence emitted in its place
    names the results file and claims nothing about the direction of the
    finding -- the report states that, under caveats this preamble does
    not attempt to restate, and check_repo.py's
    derivative-comparison-claim-stale fails the build if the old denial
    reappears while the results file exists."""
    sources_list = '\n'.join(f"- {name}" for name in DERIVATIVE_SOURCE_NAMES)
    return (
        "This file is generated by tools/generate_derivatives.py. Do not edit it by hand --\n"
        "a hand edit does not survive the next regeneration, and check_repo.py's\n"
        "skill-derivative-stale code and this script's own --check mode both catch it.\n\n"
        "It was built from the following sources, concatenated verbatim in this order:\n\n"
        f"{sources_list}\n\n"
        f"One source is deliberately left out: {OMITTED_SOURCE}. That file supplies\n"
        "illustration rather than instruction -- every rule it illustrates already carries\n"
        "its own constructive line in one of the sources listed above: the PF rules in\n"
        "skills/proof-first/SKILL.md, the MC rules in\n"
        "skills/proof-first/references/completeness-audit.md, which is where this project\n"
        "requires every MC rule to be defined. Both files are concatenated in full below, so\n"
        "nothing normative is lost by leaving the illustrations out here.\n\n"
        "Installing the skill folder at skills/proof-first/ is the fuller route: it can read\n"
        "the omitted reference file on request and keeps every reference file addressable by\n"
        "name. This project publishes measured claims or none. A benchmark has compared a\n"
        "session driven by this file against a session with the skill folder installed:\n"
        "evals/routes/RESULTS-routes.md records what was measured, what it found, and the\n"
        "caveats that bound it. Read that file rather than assuming an outcome in either\n"
        "direction from this paragraph.\n"
    )


def render_output_style(body, digest, description_block):
    """YAML frontmatter first (name, a description derived from the
    skill's own frontmatter description, and keep-coding-instructions:
    false -- no force-for-plugin key, because a writing persona should
    be opted into rather than forced), then the stamp line, then the
    generated preamble, then the shared body."""
    stamp = STAMP_TEMPLATE.format(paths=', '.join(DERIVATIVE_SOURCE_NAMES), digest=digest)
    frontmatter = (
        "---\n"
        "name: proof-first\n"
        "description: |\n"
        f"{description_block}"
        "keep-coding-instructions: false\n"
        "---\n"
    )
    return frontmatter + stamp + "\n\n" + _render_preamble() + "\n" + body


def render_system_prompt(body, digest):
    """The stamp line first, then the same generated preamble, then the
    identical shared body, with no YAML frontmatter, so the whole file
    can be pasted into a system-prompt field or an AGENTS.md without
    editing."""
    stamp = STAMP_TEMPLATE.format(paths=', '.join(DERIVATIVE_SOURCE_NAMES), digest=digest)
    return stamp + "\n\n" + _render_preamble() + "\n" + body


def _render_both(repo_root):
    blobs = read_sources(repo_root)
    digest = source_hash(blobs)
    body = build_body(blobs)
    frontmatter, _ = _skill_frontmatter_and_body(blobs[0].decode('utf-8'))
    description_block = _skill_description_block(frontmatter)
    return {
        OUTPUT_STYLE_PATH: render_output_style(body, digest, description_block),
        SYSTEM_PROMPT_PATH: render_system_prompt(body, digest),
    }


def write_derivatives(repo_root):
    """Render both derivatives and write them. The output is a pure
    function of the source bytes: calling this twice in a row on an
    unchanged tree leaves both files byte-identical. Writing utf-8
    bytes pins the output line ending to LF on every platform without
    relying on Python 3.10+'s Path.write_text(newline=...) -- without
    it, Path.write_text() translates '\\n' to os.linesep on Windows, so
    regenerating on a platform whose native line ending is CRLF would
    write different bytes than this repository ships."""
    rendered = _render_both(repo_root)
    for rel, text in rendered.items():
        path = repo_root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(text.encode('utf-8'))


def check_derivatives(repo_root):
    """Render both derivatives in memory and compare them byte for byte
    against the committed files' bytes -- the verdict is decided on
    bytes, never on decoded text, so a CRLF-terminated committed file no
    longer compares equal to an LF-terminated render under Python's
    universal-newline text-mode translation. Prints which file differs,
    and a short indication of where, for every difference found; the
    first-differing-line report decodes both byte strings defensively
    (a file that is not valid UTF-8 produces a report rather than an
    exception) but that decode is for the message only, never for the
    verdict, which has already been reached from the bytes by that
    point. A missing derivative file counts as a difference. Returns
    True only when both committed files' bytes equal freshly rendered
    output's bytes exactly."""
    rendered = _render_both(repo_root)
    ok = True
    for rel, expected_text in rendered.items():
        path = repo_root / rel
        if not path.exists():
            print(f"generate_derivatives --check: {rel} is missing -- run this script with no flag to create it")
            ok = False
            continue
        expected_bytes = expected_text.encode('utf-8')
        actual_bytes = path.read_bytes()
        if actual_bytes != expected_bytes:
            expected_lines = expected_bytes.decode('utf-8', errors='replace').splitlines()
            actual_lines = actual_bytes.decode('utf-8', errors='replace').splitlines()
            first_diff = next(
                (i for i, (a, b) in enumerate(zip(expected_lines, actual_lines)) if a != b),
                min(len(expected_lines), len(actual_lines)),
            )
            print(
                f"generate_derivatives --check: {rel} differs from freshly rendered output "
                f"starting at line {first_diff + 1} -- run this script with no flag to re-sync"
            )
            ok = False
    return ok


def main():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()

    if args.check:
        ok = check_derivatives(REPO_ROOT)
        sys.exit(0 if ok else 1)

    write_derivatives(REPO_ROOT)
    sys.exit(0)


if __name__ == '__main__':
    main()
